<template>
    <section>
        <b-card
            header-text-variant="white"
            header-tag="header"
            header-bg-variant="dark"
            style="max-width: 100vw;"
        >
        <b-col sm="5">
            <b-row>
                <b-col sm="10" md="12" fluid ><b-card-title><b-form-input type="text" @input="handleChange = true" v-model="storeInfo.exerciseName"></b-form-input></b-card-title></b-col>
                <b-col md="12" fluid><button @click="updateExerciseName" v-if="handleChange" class="generalBtn">Save Changes</button></b-col>
            </b-row>
        </b-col>
        <div class="grid-container">
            <p>Reps:</p>
            <p>Sets:</p>
            <p>Weight:</p>
            <b-button @click="deleteExercise">X</b-button>
            <b-col class="inputBoxWidth" sm="2">
                <b-form-input @input="handleChange = true" v-model="storeInfo.reps" placeholder="0"></b-form-input>
            </b-col>
            <b-col class="inputBoxWidth" sm="2">
                <b-form-input @input="handleChange = true" v-model="storeInfo.sets" placeholder="0"></b-form-input>
            </b-col>
            <b-col class="inputBoxWidth" sm="2">
                <b-form-input @input="handleChange = true" v-model="storeInfo.weight" placeholder="0"></b-form-input>
            </b-col>
        </div>
        </b-card>
    </section>
</template>

<script>
import axios from 'axios'
import cookies from 'vue-cookies'

    export default {
        name: 'WorkoutTemplateChild',
        props: {
            exerciseIdP : Number,
            exerciseNameP : String,
            repsP : Number,
            setsP : Number,
            weightP : Number,
            userIdP : Number,
            state : Boolean,

        },
        data: () => {
            return {
                allExerciseData : [],
                exerciseRow : {},
                workoutId : null,
                userToken : null,
                userId : null,
                handleChange : false,

                storeInfo : {
                    workoutId: null,
                    loginToken: null,
                    exerciseName: null,
                    reps: 1,
                    sets: 1,
                    weight: 1,
                }
            }
        },

        methods: {
            updateExerciseName() {
                axios.request({
                    url: `${process.env.VUE_APP_BASE_DOMAIN}/api/exercises`,
                    method: 'PATCH',
                    headers:{
                        'Content-Type': 'application/json'
                    },
                    data: {
                        "exerciseId" : this.exerciseIdP,
                        "userId" : this.userId,
                        "workoutId" : this.$route.params.workout,
                        "reps" : this.storeInfo.reps,
                        "sets" : this.storeInfo.sets,
                        "weight": this.storeInfo.weight,
                        "oldExerciseName": this.exerciseNameP,
                        "newExerciseName": this.storeInfo.exerciseName

                    }
                    }).then(() => {
                        this.handleChange = false

                    }).catch((error) => {
                        console.error("There was an error: " +error);
                    })
            },
            deleteExercise() {
                // Distinguish between exercises initially generated by template, or user added exercise.
                axios.request({
                url: `${process.env.VUE_APP_BASE_DOMAIN}/api/exercises`,
                method: 'DELETE',
                headers:{
                    'Content-Type': 'application/json'
                },
                data: {
                    "loginToken" : this.userToken,
                    "exerciseId" : this.exerciseIdP,
                }
                }).then(() => {
                    this.$emit('notifyParentDeleteExercise');

                }).catch((error) => {
                    console.error("There was an error: " +error);
                })
                
            },
            addDataToStore() {
                // Updates store with 'storeInfo'. All data updated via v-model
                this.$store.dispatch('loadItems',this.storeInfo)
            },
            
            initialData() {
                this.storeInfo = {
                    workoutId : this.$route.params.workout,
                    loginToken : this.userToken,
                    exerciseName : this.exerciseNameP,
                    reps: this.repsP,
                    sets: this.setsP,
                    weight: this.weightP
                }
            },
            getMyCookies() {
                var getCookie = cookies.get('loginData');
                this.userToken = getCookie.loginToken;
                this.userId = getCookie.userId;
                
            },
        },
        mounted() {
            this.getMyCookies();
            this.initialData();
        },
        watch: {
            state() {
                this.addDataToStore();
            },
        }
    }
</script>

<style lang="scss" scoped>
    .grid-container {
        display: grid;
        grid-template-columns: repeat(4, 1fr);
        grid-template-rows: repeat(2, 1fr);
    }
    .inputBoxWidth {
        width: 50px;
    }
    #checkbox-1 {
        width: 30px;
    }
    .generalBtn {
        padding: 0 40px;
    }
    
</style>